import * as Clipboard from "expo-clipboard";
import { router, useLocalSearchParams } from "expo-router";
import { useCallback, useEffect, useRef, useState } from "react";
import { Share } from "react-native";

import { Button, Card, ErrorText, Loading, Markdown, Muted, Row, Screen, Title } from "../../../components/ui";
import { api, ApiError, DocumentDetail, pagesLabel, SummaryStyle } from "../../../lib/api";

type Item = { id: string; title: string; pages: string; summary?: string; error?: string; loading: boolean };

export default function Summary() {
  const { id, ids, style } = useLocalSearchParams<{ id: string; ids: string; style: SummaryStyle }>();
  const [doc, setDoc] = useState<DocumentDetail | null>(null);
  const [items, setItems] = useState<Item[]>([]);
  const [done, setDone] = useState(false);
  const [error, setError] = useState("");
  const [copied, setCopied] = useState(false);
  // Bumped on regenerate/unmount so an in-flight loop stops updating state.
  const run = useRef({ token: 0 });

  const generate = useCallback(async (d: DocumentDetail, refresh: boolean) => {
    const token = ++run.current.token;
    const byId = new Map(d.sections.map(s => [s.id, s]));
    const list: Item[] = (ids || "").split(",").filter(Boolean).map(sid => {
      const s = byId.get(sid);
      return { id: sid, title: s?.title ?? sid, pages: s ? pagesLabel(s.page_start, s.page_end) : "", loading: true };
    });
    setItems(list);

    // One request per section so summaries appear as soon as each is ready.
    for (const item of list) {
      if (run.current.token !== token) return; // screen left or regenerate pressed
      try {
        const res = await api.summarize(id, [item.id], style || "brief", refresh);
        item.summary = res.summaries[0].summary;
      } catch (e) {
        item.error = (e as ApiError).message;
      }
      item.loading = false;
      if (run.current.token === token) setItems([...list]);
    }
    if (run.current.token === token) setDone(true);
  }, [id, ids, style]);

  useEffect(() => {
    const r = run.current;
    api.getDocument(id)
      .then(d => {
        setDoc(d);
        return generate(d, false);
      })
      .catch(e => setError((e as ApiError).message));
    return () => { r.token++; };
  }, [id, generate]);

  const markdown = () =>
    `# Summary: ${doc?.filename ?? ""}\n\n` +
    items.filter(i => i.summary).map(i => `## ${i.title}\n\n${i.summary}\n`).join("\n");

  return (
    <Screen>
      <Row style={{ justifyContent: "space-between" }}>
        <Button small variant="ghost" label="← Back to sections" onPress={() => router.back()} />
        <Button small variant="ghost" label="⌂ Home" onPress={() => router.dismissTo("/")} />
      </Row>

      {doc ? <Title>{doc.filename}</Title> : null}
      <Muted>{items.length} section(s) · style: {style} · generated by Qwen on your server</Muted>
      <ErrorText>{error}</ErrorText>

      {items.map(item => (
        <Card key={item.id}>
          <Title style={{ fontSize: 17 }}>{item.title}</Title>
          {item.pages ? <Muted>{item.pages}</Muted> : null}
          {item.loading ? (
            <Loading label="Summarizing…" />
          ) : item.error ? (
            <ErrorText>{item.error}</ErrorText>
          ) : (
            <Markdown text={item.summary ?? ""} />
          )}
        </Card>
      ))}

      {done ? (
        <Row>
          <Button
            variant="ghost"
            label={copied ? "Copied ✓" : "Copy"}
            onPress={async () => {
              await Clipboard.setStringAsync(markdown());
              setCopied(true);
              setTimeout(() => setCopied(false), 1500);
            }}
          />
          <Button variant="ghost" label="Share" onPress={() => Share.share({ message: markdown(), title: doc?.filename })} />
          <Button variant="ghost" label="Regenerate" onPress={() => { if (doc) { setDone(false); generate(doc, true); } }} />
        </Row>
      ) : null}

      <Row style={{ marginTop: 8 }}>
        <Button label="← Back to sections" onPress={() => router.back()} style={{ flex: 1 }} />
        <Button variant="ghost" label="⌂ Home" onPress={() => router.dismissTo("/")} style={{ flex: 1 }} />
      </Row>
    </Screen>
  );
}
